### ISSUE TITLE
Errors when running "npm start"

### ISSUE THREAD

**Issue by camgullo** [PufferPanel/gsd#19]
Hello,
I am running Ubuntu 14.04 (64 bit).
I follow the installer copying and pasting the commands as root. (Installing the dependencies first)
Running "npm install" seems to work fine. When running "npm start" I get a bunch of errors. Here is the log file... http://pastebin.com/g1PZ068P 
I don't get any errors in any part of the installation except in "npm start".

**Comment by koo04** [comment]
Can you post what the logs say under /srv/gsd/logs?

**Comment by DaneEveritt** [comment]
@koo04 – pretty sure he never gets far enough to have GSD actually begin running.

**Comment by camgullo** [comment]
Yeah I havent gotten GSD running yet.

**Comment by koo04** [comment]
I have been trying to replicate this issue all morning with no luck. Can you give me the exact steps you did to get this issue? Are you able to replicate it again with a fresh start?

**Comment by DaneEveritt** [comment]
@camgullo — just to confirm you are doing `git checkout tag/0.1.4`?

**Comment by camgullo** [comment]
Looks like I may have had outdated packages before. I did a full rebuild, update, and upgrade, and re-followed all of the steps with success.

Thanks to both of you for helping.
