### ISSUE TITLE
Issue with starting the GSD

### ISSUE THREAD

**Issue by Beariful** [PufferPanel/gsd#22]
I have been messing around with this for while, have tried reinstalling packages and what not.

My Debug file:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart GameServerDaemon@0.1.4
7 info start GameServerDaemon@0.1.4
8 verbose unsafe-perm in lifecycle true
9 info GameServerDaemon@0.1.4 Failed to exec start script
10 error GameServerDaemon@0.1.4 start: `node gsd.js`
10 error Exit status 8
11 error Failed at the GameServerDaemon@0.1.4 start script.
11 error This is most likely a problem with the GameServerDaemon package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     node gsd.js
11 error You can get their info via:
11 error     npm owner ls GameServerDaemon
11 error There is likely additional logging output above.
12 error System Linux 3.13.0-36-generic
13 error command "/usr/bin/node" "/usr/bin/npm" "start"
14 error cwd /srv/gsd
15 error node -v v0.10.33
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

**Comment by DaneEveritt** [comment]
I am assuming that since you closed it you fixed the problem?
